-- Migration 055: Context-Aware AI Suggestions
-- Part of Phase 2.0: Intelligence Layer
-- Created: 2025-12-02

-- Track GPT API usage for cost monitoring
CREATE TABLE IF NOT EXISTS gpt_usage_log (
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_type TEXT NOT NULL,  -- 'suggestion_analysis', 'context_build', etc.
    model TEXT NOT NULL DEFAULT 'gpt-4o-mini',
    input_tokens INTEGER,
    output_tokens INTEGER,
    estimated_cost_usd REAL,
    email_ids TEXT,  -- JSON array of email IDs processed
    batch_size INTEGER DEFAULT 1,
    processing_time_ms INTEGER,
    success INTEGER DEFAULT 1,
    error_message TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Index for cost analysis
CREATE INDEX IF NOT EXISTS idx_gpt_usage_created_at ON gpt_usage_log(created_at);
CREATE INDEX IF NOT EXISTS idx_gpt_usage_request_type ON gpt_usage_log(request_type);

-- Add new suggestion types to support context-aware analysis
-- Note: SQLite requires table recreation to modify CHECK constraints
-- Instead, we'll just insert valid values - the application will validate

-- Track context-aware mode settings
CREATE TABLE IF NOT EXISTS ai_config (
    config_key TEXT PRIMARY KEY,
    config_value TEXT NOT NULL,
    description TEXT,
    updated_at TEXT DEFAULT (datetime('now')),
    updated_by TEXT
);

-- Insert default configuration
INSERT OR IGNORE INTO ai_config (config_key, config_value, description)
VALUES
    ('use_context_aware_suggestions', 'false', 'Enable GPT-powered context-aware suggestion generation'),
    ('context_cache_ttl_seconds', '300', 'Time-to-live for context bundle cache'),
    ('gpt_model', 'gpt-4o-mini', 'OpenAI model to use for analysis'),
    ('gpt_max_tokens_per_request', '2000', 'Maximum tokens for GPT response'),
    ('suggestion_confidence_threshold', '0.6', 'Minimum confidence to create suggestion');

-- Add column to track which suggestions were generated by context-aware system
-- (If column doesn't exist)
-- ALTER TABLE ai_suggestions ADD COLUMN generation_method TEXT DEFAULT 'rule_based';
-- Note: Run this manually if needed - SQLite ALTER TABLE is limited

-- View for GPT usage summary
CREATE VIEW IF NOT EXISTS gpt_usage_summary AS
SELECT
    DATE(created_at) as date,
    request_type,
    COUNT(*) as request_count,
    SUM(input_tokens) as total_input_tokens,
    SUM(output_tokens) as total_output_tokens,
    SUM(estimated_cost_usd) as total_cost_usd,
    AVG(processing_time_ms) as avg_processing_time_ms,
    SUM(batch_size) as emails_processed,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as successful_requests,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failed_requests
FROM gpt_usage_log
GROUP BY DATE(created_at), request_type;

-- Monthly cost summary
CREATE VIEW IF NOT EXISTS gpt_monthly_cost AS
SELECT
    strftime('%Y-%m', created_at) as month,
    SUM(estimated_cost_usd) as total_cost_usd,
    SUM(input_tokens) as total_input_tokens,
    SUM(output_tokens) as total_output_tokens,
    COUNT(*) as total_requests,
    SUM(batch_size) as total_emails_processed
FROM gpt_usage_log
WHERE success = 1
GROUP BY strftime('%Y-%m', created_at);
